export type CountryInfo = {
  code: string;
  name: string;
  currencySymbol: string;
  currencyCode: string;
  exchangeRate: number; // 1 USD = X local currency (approximate)
};

export const ALL_COUNTRIES: CountryInfo[] = [
  // ── Popular / Featured first ──
  { code: "US", name: "United States", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "GB", name: "United Kingdom", currencySymbol: "£", currencyCode: "GBP", exchangeRate: 0.79 },
  { code: "CA", name: "Canada", currencySymbol: "C$", currencyCode: "CAD", exchangeRate: 1.38 },
  { code: "AU", name: "Australia", currencySymbol: "A$", currencyCode: "AUD", exchangeRate: 1.55 },
  { code: "NG", name: "Nigeria", currencySymbol: "₦", currencyCode: "NGN", exchangeRate: 1600 },
  { code: "GH", name: "Ghana", currencySymbol: "₵", currencyCode: "GHS", exchangeRate: 15 },
  { code: "ZA", name: "South Africa", currencySymbol: "R", currencyCode: "ZAR", exchangeRate: 18.5 },
  { code: "KE", name: "Kenya", currencySymbol: "KSh", currencyCode: "KES", exchangeRate: 130 },
  { code: "IN", name: "India", currencySymbol: "₹", currencyCode: "INR", exchangeRate: 83 },
  { code: "AE", name: "United Arab Emirates", currencySymbol: "د.إ", currencyCode: "AED", exchangeRate: 3.67 },

  // ── Africa ──
  { code: "DZ", name: "Algeria", currencySymbol: "دج", currencyCode: "DZD", exchangeRate: 134 },
  { code: "AO", name: "Angola", currencySymbol: "Kz", currencyCode: "AOA", exchangeRate: 850 },
  { code: "BJ", name: "Benin", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "BW", name: "Botswana", currencySymbol: "P", currencyCode: "BWP", exchangeRate: 13.5 },
  { code: "BF", name: "Burkina Faso", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "BI", name: "Burundi", currencySymbol: "Fr", currencyCode: "BIF", exchangeRate: 2870 },
  { code: "CV", name: "Cabo Verde", currencySymbol: "$", currencyCode: "CVE", exchangeRate: 104 },
  { code: "CM", name: "Cameroon", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "CF", name: "Central African Republic", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "TD", name: "Chad", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "KM", name: "Comoros", currencySymbol: "Fr", currencyCode: "KMF", exchangeRate: 450 },
  { code: "CG", name: "Congo", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "CD", name: "Democratic Republic of the Congo", currencySymbol: "Fr", currencyCode: "CDF", exchangeRate: 2760 },
  { code: "DJ", name: "Djibouti", currencySymbol: "Fr", currencyCode: "DJF", exchangeRate: 178 },
  { code: "EG", name: "Egypt", currencySymbol: "£", currencyCode: "EGP", exchangeRate: 48 },
  { code: "GQ", name: "Equatorial Guinea", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "ER", name: "Eritrea", currencySymbol: "Nfk", currencyCode: "ERN", exchangeRate: 15 },
  { code: "SZ", name: "Eswatini", currencySymbol: "L", currencyCode: "SZL", exchangeRate: 18.5 },
  { code: "ET", name: "Ethiopia", currencySymbol: "Br", currencyCode: "ETB", exchangeRate: 57 },
  { code: "GA", name: "Gabon", currencySymbol: "₣", currencyCode: "XAF", exchangeRate: 600 },
  { code: "GM", name: "Gambia", currencySymbol: "D", currencyCode: "GMD", exchangeRate: 68 },
  { code: "GN", name: "Guinea", currencySymbol: "Fr", currencyCode: "GNF", exchangeRate: 8600 },
  { code: "GW", name: "Guinea-Bissau", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "CI", name: "Ivory Coast", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "LS", name: "Lesotho", currencySymbol: "L", currencyCode: "LSL", exchangeRate: 18.5 },
  { code: "LR", name: "Liberia", currencySymbol: "$", currencyCode: "LRD", exchangeRate: 194 },
  { code: "LY", name: "Libya", currencySymbol: "LD", currencyCode: "LYD", exchangeRate: 4.8 },
  { code: "MG", name: "Madagascar", currencySymbol: "Ar", currencyCode: "MGA", exchangeRate: 4600 },
  { code: "MW", name: "Malawi", currencySymbol: "MK", currencyCode: "MWK", exchangeRate: 1730 },
  { code: "ML", name: "Mali", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "MR", name: "Mauritania", currencySymbol: "UM", currencyCode: "MRU", exchangeRate: 39 },
  { code: "MU", name: "Mauritius", currencySymbol: "₨", currencyCode: "MUR", exchangeRate: 46 },
  { code: "MA", name: "Morocco", currencySymbol: "د.م.", currencyCode: "MAD", exchangeRate: 10 },
  { code: "MZ", name: "Mozambique", currencySymbol: "MT", currencyCode: "MZN", exchangeRate: 64 },
  { code: "NA", name: "Namibia", currencySymbol: "N$", currencyCode: "NAD", exchangeRate: 18.5 },
  { code: "NE", name: "Niger", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "RW", name: "Rwanda", currencySymbol: "Fr", currencyCode: "RWF", exchangeRate: 1300 },
  { code: "ST", name: "Sao Tome and Principe", currencySymbol: "Db", currencyCode: "STN", exchangeRate: 23 },
  { code: "SN", name: "Senegal", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "SC", name: "Seychelles", currencySymbol: "₨", currencyCode: "SCR", exchangeRate: 14 },
  { code: "SL", name: "Sierra Leone", currencySymbol: "Le", currencyCode: "SLE", exchangeRate: 22 },
  { code: "SO", name: "Somalia", currencySymbol: "Sh", currencyCode: "SOS", exchangeRate: 571 },
  { code: "SS", name: "South Sudan", currencySymbol: "£", currencyCode: "SSP", exchangeRate: 1300 },
  { code: "SD", name: "Sudan", currencySymbol: "£", currencyCode: "SDG", exchangeRate: 600 },
  { code: "TZ", name: "Tanzania", currencySymbol: "Sh", currencyCode: "TZS", exchangeRate: 2600 },
  { code: "TG", name: "Togo", currencySymbol: "₣", currencyCode: "XOF", exchangeRate: 600 },
  { code: "TN", name: "Tunisia", currencySymbol: "دت", currencyCode: "TND", exchangeRate: 3.1 },
  { code: "UG", name: "Uganda", currencySymbol: "Sh", currencyCode: "UGX", exchangeRate: 3750 },
  { code: "ZM", name: "Zambia", currencySymbol: "ZK", currencyCode: "ZMW", exchangeRate: 27 },
  { code: "ZW", name: "Zimbabwe", currencySymbol: "ZWG", currencyCode: "ZWG", exchangeRate: 14 },

  // ── Asia ──
  { code: "AF", name: "Afghanistan", currencySymbol: "؋", currencyCode: "AFN", exchangeRate: 70 },
  { code: "AM", name: "Armenia", currencySymbol: "֏", currencyCode: "AMD", exchangeRate: 390 },
  { code: "AZ", name: "Azerbaijan", currencySymbol: "₼", currencyCode: "AZN", exchangeRate: 1.7 },
  { code: "BH", name: "Bahrain", currencySymbol: "BD", currencyCode: "BHD", exchangeRate: 0.38 },
  { code: "BD", name: "Bangladesh", currencySymbol: "৳", currencyCode: "BDT", exchangeRate: 110 },
  { code: "BT", name: "Bhutan", currencySymbol: "Nu", currencyCode: "BTN", exchangeRate: 83 },
  { code: "BN", name: "Brunei", currencySymbol: "B$", currencyCode: "BND", exchangeRate: 1.35 },
  { code: "KH", name: "Cambodia", currencySymbol: "៛", currencyCode: "KHR", exchangeRate: 4100 },
  { code: "CN", name: "China", currencySymbol: "¥", currencyCode: "CNY", exchangeRate: 7.25 },
  { code: "CY", name: "Cyprus", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "GE", name: "Georgia", currencySymbol: "₾", currencyCode: "GEL", exchangeRate: 2.7 },
  { code: "ID", name: "Indonesia", currencySymbol: "Rp", currencyCode: "IDR", exchangeRate: 15800 },
  { code: "IR", name: "Iran", currencySymbol: "﷼", currencyCode: "IRR", exchangeRate: 42000 },
  { code: "IQ", name: "Iraq", currencySymbol: "ع.د", currencyCode: "IQD", exchangeRate: 1310 },
  { code: "IL", name: "Israel", currencySymbol: "₪", currencyCode: "ILS", exchangeRate: 3.7 },
  { code: "JP", name: "Japan", currencySymbol: "¥", currencyCode: "JPY", exchangeRate: 150 },
  { code: "JO", name: "Jordan", currencySymbol: "JD", currencyCode: "JOD", exchangeRate: 0.71 },
  { code: "KZ", name: "Kazakhstan", currencySymbol: "₸", currencyCode: "KZT", exchangeRate: 470 },
  { code: "KW", name: "Kuwait", currencySymbol: "KD", currencyCode: "KWD", exchangeRate: 0.31 },
  { code: "KG", name: "Kyrgyzstan", currencySymbol: "с", currencyCode: "KGS", exchangeRate: 87 },
  { code: "LA", name: "Laos", currencySymbol: "₭", currencyCode: "LAK", exchangeRate: 21700 },
  { code: "LB", name: "Lebanon", currencySymbol: "£", currencyCode: "LBP", exchangeRate: 89500 },
  { code: "MY", name: "Malaysia", currencySymbol: "RM", currencyCode: "MYR", exchangeRate: 4.7 },
  { code: "MV", name: "Maldives", currencySymbol: "ل.ر", currencyCode: "MVR", exchangeRate: 15.4 },
  { code: "MN", name: "Mongolia", currencySymbol: "₮", currencyCode: "MNT", exchangeRate: 3450 },
  { code: "MM", name: "Myanmar", currencySymbol: "K", currencyCode: "MMK", exchangeRate: 2100 },
  { code: "NP", name: "Nepal", currencySymbol: "₨", currencyCode: "NPR", exchangeRate: 133 },
  { code: "KP", name: "North Korea", currencySymbol: "₩", currencyCode: "KPW", exchangeRate: 900 },
  { code: "OM", name: "Oman", currencySymbol: "﷼", currencyCode: "OMR", exchangeRate: 0.38 },
  { code: "PK", name: "Pakistan", currencySymbol: "₨", currencyCode: "PKR", exchangeRate: 280 },
  { code: "PS", name: "Palestine", currencySymbol: "₪", currencyCode: "ILS", exchangeRate: 3.7 },
  { code: "PH", name: "Philippines", currencySymbol: "₱", currencyCode: "PHP", exchangeRate: 56 },
  { code: "QA", name: "Qatar", currencySymbol: "﷼", currencyCode: "QAR", exchangeRate: 3.64 },
  { code: "SA", name: "Saudi Arabia", currencySymbol: "﷼", currencyCode: "SAR", exchangeRate: 3.75 },
  { code: "SG", name: "Singapore", currencySymbol: "S$", currencyCode: "SGD", exchangeRate: 1.35 },
  { code: "KR", name: "South Korea", currencySymbol: "₩", currencyCode: "KRW", exchangeRate: 1340 },
  { code: "LK", name: "Sri Lanka", currencySymbol: "₨", currencyCode: "LKR", exchangeRate: 300 },
  { code: "SY", name: "Syria", currencySymbol: "£", currencyCode: "SYP", exchangeRate: 13000 },
  { code: "TJ", name: "Tajikistan", currencySymbol: "SM", currencyCode: "TJS", exchangeRate: 10.9 },
  { code: "TH", name: "Thailand", currencySymbol: "฿", currencyCode: "THB", exchangeRate: 36 },
  { code: "TL", name: "Timor-Leste", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "TR", name: "Turkey", currencySymbol: "₺", currencyCode: "TRY", exchangeRate: 32 },
  { code: "TM", name: "Turkmenistan", currencySymbol: "T", currencyCode: "TMT", exchangeRate: 3.5 },
  { code: "UZ", name: "Uzbekistan", currencySymbol: "so'm", currencyCode: "UZS", exchangeRate: 12700 },
  { code: "VN", name: "Vietnam", currencySymbol: "₫", currencyCode: "VND", exchangeRate: 24800 },
  { code: "YE", name: "Yemen", currencySymbol: "﷼", currencyCode: "YER", exchangeRate: 250 },

  // ── Europe ──
  { code: "AL", name: "Albania", currencySymbol: "L", currencyCode: "ALL", exchangeRate: 96 },
  { code: "AD", name: "Andorra", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "AT", name: "Austria", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "BY", name: "Belarus", currencySymbol: "Br", currencyCode: "BYN", exchangeRate: 3.3 },
  { code: "BE", name: "Belgium", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "BA", name: "Bosnia and Herzegovina", currencySymbol: "KM", currencyCode: "BAM", exchangeRate: 1.82 },
  { code: "BG", name: "Bulgaria", currencySymbol: "лв", currencyCode: "BGN", exchangeRate: 1.82 },
  { code: "HR", name: "Croatia", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "CZ", name: "Czech Republic", currencySymbol: "Kč", currencyCode: "CZK", exchangeRate: 23 },
  { code: "DK", name: "Denmark", currencySymbol: "kr", currencyCode: "DKK", exchangeRate: 6.9 },
  { code: "EE", name: "Estonia", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "FI", name: "Finland", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "FR", name: "France", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "DE", name: "Germany", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "GR", name: "Greece", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "HU", name: "Hungary", currencySymbol: "Ft", currencyCode: "HUF", exchangeRate: 360 },
  { code: "IS", name: "Iceland", currencySymbol: "kr", currencyCode: "ISK", exchangeRate: 138 },
  { code: "IE", name: "Ireland", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "IT", name: "Italy", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "XK", name: "Kosovo", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "LV", name: "Latvia", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "LI", name: "Liechtenstein", currencySymbol: "Fr", currencyCode: "CHF", exchangeRate: 0.9 },
  { code: "LT", name: "Lithuania", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "LU", name: "Luxembourg", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "MT", name: "Malta", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "MD", name: "Moldova", currencySymbol: "L", currencyCode: "MDL", exchangeRate: 17.7 },
  { code: "MC", name: "Monaco", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "ME", name: "Montenegro", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "NL", name: "Netherlands", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "MK", name: "North Macedonia", currencySymbol: "ден", currencyCode: "MKD", exchangeRate: 57 },
  { code: "NO", name: "Norway", currencySymbol: "kr", currencyCode: "NOK", exchangeRate: 10.6 },
  { code: "PL", name: "Poland", currencySymbol: "zł", currencyCode: "PLN", exchangeRate: 4.0 },
  { code: "PT", name: "Portugal", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "RO", name: "Romania", currencySymbol: "lei", currencyCode: "RON", exchangeRate: 4.6 },
  { code: "RU", name: "Russia", currencySymbol: "₽", currencyCode: "RUB", exchangeRate: 91 },
  { code: "SM", name: "San Marino", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "RS", name: "Serbia", currencySymbol: "din", currencyCode: "RSD", exchangeRate: 108 },
  { code: "SK", name: "Slovakia", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "SI", name: "Slovenia", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "ES", name: "Spain", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },
  { code: "SE", name: "Sweden", currencySymbol: "kr", currencyCode: "SEK", exchangeRate: 10.4 },
  { code: "CH", name: "Switzerland", currencySymbol: "Fr", currencyCode: "CHF", exchangeRate: 0.9 },
  { code: "UA", name: "Ukraine", currencySymbol: "₴", currencyCode: "UAH", exchangeRate: 40 },
  { code: "VA", name: "Vatican City", currencySymbol: "€", currencyCode: "EUR", exchangeRate: 0.93 },

  // ── Latin America & Caribbean ──
  { code: "AG", name: "Antigua and Barbuda", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "AR", name: "Argentina", currencySymbol: "$", currencyCode: "ARS", exchangeRate: 900 },
  { code: "BS", name: "Bahamas", currencySymbol: "$", currencyCode: "BSD", exchangeRate: 1 },
  { code: "BB", name: "Barbados", currencySymbol: "Bds$", currencyCode: "BBD", exchangeRate: 2 },
  { code: "BZ", name: "Belize", currencySymbol: "BZ$", currencyCode: "BZD", exchangeRate: 2 },
  { code: "BO", name: "Bolivia", currencySymbol: "Bs.", currencyCode: "BOB", exchangeRate: 6.9 },
  { code: "BR", name: "Brazil", currencySymbol: "R$", currencyCode: "BRL", exchangeRate: 5 },
  { code: "CL", name: "Chile", currencySymbol: "$", currencyCode: "CLP", exchangeRate: 930 },
  { code: "CO", name: "Colombia", currencySymbol: "$", currencyCode: "COP", exchangeRate: 3950 },
  { code: "CR", name: "Costa Rica", currencySymbol: "₡", currencyCode: "CRC", exchangeRate: 515 },
  { code: "CU", name: "Cuba", currencySymbol: "$", currencyCode: "CUP", exchangeRate: 24 },
  { code: "DM", name: "Dominica", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "DO", name: "Dominican Republic", currencySymbol: "RD$", currencyCode: "DOP", exchangeRate: 59 },
  { code: "EC", name: "Ecuador", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "SV", name: "El Salvador", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "GD", name: "Grenada", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "GT", name: "Guatemala", currencySymbol: "Q", currencyCode: "GTQ", exchangeRate: 7.8 },
  { code: "GY", name: "Guyana", currencySymbol: "G$", currencyCode: "GYD", exchangeRate: 209 },
  { code: "HT", name: "Haiti", currencySymbol: "G", currencyCode: "HTG", exchangeRate: 132 },
  { code: "HN", name: "Honduras", currencySymbol: "L", currencyCode: "HNL", exchangeRate: 24.7 },
  { code: "JM", name: "Jamaica", currencySymbol: "J$", currencyCode: "JMD", exchangeRate: 156 },
  { code: "MX", name: "Mexico", currencySymbol: "MX$", currencyCode: "MXN", exchangeRate: 17.5 },
  { code: "NI", name: "Nicaragua", currencySymbol: "C$", currencyCode: "NIO", exchangeRate: 36.6 },
  { code: "PA", name: "Panama", currencySymbol: "B/.", currencyCode: "PAB", exchangeRate: 1 },
  { code: "PY", name: "Paraguay", currencySymbol: "₲", currencyCode: "PYG", exchangeRate: 7500 },
  { code: "PE", name: "Peru", currencySymbol: "S/.", currencyCode: "PEN", exchangeRate: 3.7 },
  { code: "KN", name: "Saint Kitts and Nevis", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "LC", name: "Saint Lucia", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "VC", name: "Saint Vincent and the Grenadines", currencySymbol: "EC$", currencyCode: "XCD", exchangeRate: 2.7 },
  { code: "SR", name: "Suriname", currencySymbol: "Sr$", currencyCode: "SRD", exchangeRate: 36 },
  { code: "TT", name: "Trinidad and Tobago", currencySymbol: "TT$", currencyCode: "TTD", exchangeRate: 6.8 },
  { code: "UY", name: "Uruguay", currencySymbol: "$U", currencyCode: "UYU", exchangeRate: 38 },
  { code: "VE", name: "Venezuela", currencySymbol: "Bs.D", currencyCode: "VES", exchangeRate: 36 },

  // ── Oceania ──
  { code: "FJ", name: "Fiji", currencySymbol: "FJ$", currencyCode: "FJD", exchangeRate: 2.25 },
  { code: "KI", name: "Kiribati", currencySymbol: "A$", currencyCode: "AUD", exchangeRate: 1.55 },
  { code: "MH", name: "Marshall Islands", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "FM", name: "Micronesia", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "NR", name: "Nauru", currencySymbol: "A$", currencyCode: "AUD", exchangeRate: 1.55 },
  { code: "NZ", name: "New Zealand", currencySymbol: "NZ$", currencyCode: "NZD", exchangeRate: 1.65 },
  { code: "PW", name: "Palau", currencySymbol: "$", currencyCode: "USD", exchangeRate: 1 },
  { code: "PG", name: "Papua New Guinea", currencySymbol: "K", currencyCode: "PGK", exchangeRate: 3.8 },
  { code: "WS", name: "Samoa", currencySymbol: "T", currencyCode: "WST", exchangeRate: 2.75 },
  { code: "SB", name: "Solomon Islands", currencySymbol: "SI$", currencyCode: "SBD", exchangeRate: 8.5 },
  { code: "TO", name: "Tonga", currencySymbol: "T$", currencyCode: "TOP", exchangeRate: 2.4 },
  { code: "TV", name: "Tuvalu", currencySymbol: "A$", currencyCode: "AUD", exchangeRate: 1.55 },
  { code: "VU", name: "Vanuatu", currencySymbol: "VT", currencyCode: "VUV", exchangeRate: 119 },
];

export function getCountryByCode(code: string): CountryInfo | undefined {
  return ALL_COUNTRIES.find(c => c.code === code);
}

export function getLocalCurrency(country?: string | null): { symbol: string; rate: number; name: string } | null {
  if (!country) return null;
  const info = ALL_COUNTRIES.find(c => c.code === country.toUpperCase());
  if (!info || info.currencyCode === "USD") return null;
  return { symbol: info.currencySymbol, rate: info.exchangeRate, name: info.currencyCode };
}
